### PR TITLE
Added Sphinx integration, built initial files 

### PR DESCRIPTION
**Pull request by julianstanley**
Alright, does this work as a first pass? Since I'm new to this, I don't understand why my "_build" directory doesn't show up in the commits, for example. Comments/advice very welcome!

I think once this merges (and I rebuild), then  [https://edgepy.readthedocs.io/](https://edgepy.readthedocs.io/ ) should look like [https://edgepy.readthedocs.io/en/js_docs_issue_26/](https://edgepy.readthedocs.io/en/js_docs_issue_26/) does now. 

Changes:

* Added header to Links.md and planned_statistical_tests.md files
* Created Makefile, conf.py, and make.bat files, which are used to build the Sphinx documentation files.
* Created index.rst, the documentation homepage.

Scope:
I think this is just the basic groundwork for documentation. Using autodoc can come later. Contributes to, but does not close issue #26.

### CODE REVIEW

**Comment by clintval** [comment]
@julianstanley this is why.

https://github.com/r-bioinformatics/edgePy/blob/1d53f92dcd94c876536e275ad723df98aa8d8b5e/.gitignore#L85

Probably for the best. I'll take a look at this PR later today! Thanks!

**Comment by julianstanley** [comment]
Addressing change request:

> What install dependencies does this need? Could you consider adding them all to a requirement group in setup.py?

This needs Sphinx and then there's another extra package for markdown support. Added under the extras_require dictionary in setup.py

> Also adding a few lines at the end of our CONTRIBUTING.md to show how to build the docs and release a new version (if applicable).

Added!

**Comment by clintval** [comment]
This also closes #31.

**Comment by julianstanley** [comment]
@clintval I'll read more about rebasing/etc, thank you! 

And yeah, the HTML adding thing was my misunderstanding. After playing around with readthedocs.org some, I noticed that it works just like Travis does--it re-builds with each new commit. So readthedocs.org reads the conf.py file in /docs, which directs it to display the index.rst file, which in turn display the rest of the docs. 

So the whole HTML build thing is just for local testing--so you can see what the readthedocs.org output will be before you commit. Thus is being in the gitignore. 

I updated the contributing section accordingly!

**Pull request merged**
